#!/bin/sh

MYMPD_HOST="http://host:port"
MUSIC_DIR="/mnt"

uri=$(curl "$MYMPD_HOST/api/default" \
  -s \
  -X POST \
  -H 'Content-Type: application/json' \
  -d '{"jsonrpc":"2.0","id":0,"method":"MYMPD_API_PLAYER_CURRENT_SONG","params":{}}' | jq -r .result.uri)

echo "$MUSIC_DIR/$uri"
dolphin --new-window --select "$MUSIC_DIR/$uri" &
