#!/bin/sh

# now playing script: it opens directory with now playing song

MYMPD_HOST="http://host:port"

uri=$(curl "$MYMPD_HOST/api/default" \
  -s \
  -X POST \
  -H 'Content-Type: application/json' \
  -d '{"jsonrpc":"2.0","id":0,"method":"MYMPD_API_PLAYER_CURRENT_SONG","params":{}}' | jq -r .result.uri)

echo "/mnt/$uri"
dolphin --new-window --select "/mnt/$uri" &
